name: day_navigator
description: A simple Flutter widget to navigate between days with arrows and a date picker. Great for calendars, schedules, and reminders.
version: 0.1.8

repository: https://github.com/AbuShebin/day_navigator
homepage: https://pub.dev/packages/day_navigator

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
